/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef im_CONSTANTS_H
#define im_CONSTANTS_H

#include "im_types.h"

namespace LW {

class imConstants {
 public:
  imConstants();

};

extern const imConstants g_im_constants;

} // namespace

#endif
