/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "im_constants.h"

namespace LW {

const imConstants g_im_constants;

imConstants::imConstants() {
}

} // namespace

