/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "package_constants.h"

namespace LW {

const packageConstants g_package_constants;

packageConstants::packageConstants() {
}

} // namespace

